import discrete_event_control_observation_systems_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace discrete_event_control_observation_systems_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end discrete_event_control_observation_systems_theorem_canonical_lane_mathlib
end HautevilleHouse
